birthday:
  month: 6
  day: 14

early_morning:
  start_hour: 6
  start_min: 15
  end_hour: 6
  end_min: 45

early_night:
  start_hour: 4
  start_min: 60
  end_hour: 5
  end_min: 10

late_morning:
  start_hour: 4
  start_min: 60
  end_hour: 5
  end_min: 10

late_night:
  start_hour: 4
  start_min: 60
  end_hour: 5
  end_min: 10


# new version
early_morning_start:
  hour: 6
  minute: 15
  second: 0

early_morning_end:
  hour: 6
  minute: 45
  second: 0

early_night_start:
  hour: 21
  minute: 0
  second: 0

early_night_end:
  hour: 22
  minute: 15
  second: 0

late_morning_start:
  hour: 9
  minute: 0
  second: 0

late_morning_end:
  hour: 10
  minute: 30
  second: 0

late_night_start:
  hour: 22
  minute: 30
  second: 0

late_night_end:
  hour: 23
  minute: 30
  second: 0



